# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("message.proto", :syntax => :proto3) do
    add_message "Proto.Message.Vector3" do
      optional :x, :int32, 1
      optional :y, :int32, 2
      optional :z, :int32, 3
    end
    add_message "Proto.Message.Entity" do
      optional :id, :int32, 1
      optional :speed, :int32, 2
      optional :position, :message, 3, "Proto.Message.Vector3"
      optional :rotation, :message, 4, "Proto.Message.Vector3"
    end
    add_message "Proto.Message.Package" do
      optional :request, :message, 1, "Proto.Message.Request"
      optional :response, :message, 2, "Proto.Message.Response"
    end
    add_message "Proto.Message.Request" do
      optional :userRegister, :message, 1, "Proto.Message.UserRegisterRequest"
      optional :userLogin, :message, 2, "Proto.Message.UserLoginRequest"
    end
    add_message "Proto.Message.Response" do
      optional :userRegister, :message, 1, "Proto.Message.UserRegisterResponse"
      optional :userLogin, :message, 2, "Proto.Message.UserLoginResponse"
    end
    add_message "Proto.Message.UserRegisterRequest" do
      optional :username, :string, 1
      optional :password, :string, 2
    end
    add_message "Proto.Message.UserRegisterResponse" do
      optional :code, :int32, 1
      optional :message, :string, 2
    end
    add_message "Proto.Message.UserLoginRequest" do
      optional :username, :string, 1
      optional :password, :string, 2
    end
    add_message "Proto.Message.UserLoginResponse" do
      optional :code, :int32, 1
      optional :message, :string, 2
    end
    add_message "Proto.Message.PlayerInput" do
      optional :inputX, :int32, 1
      optional :inputZ, :int32, 2
      optional :mousePosX, :int32, 3
      optional :mousePosZ, :int32, 4
      optional :inputFire, :bool, 5
      optional :skillId, :int32, 6
      optional :inputSpeedUp, :bool, 7
    end
  end
end

module Proto
  module Message
    Vector3 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Proto.Message.Vector3").msgclass
    Entity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Proto.Message.Entity").msgclass
    Package = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Proto.Message.Package").msgclass
    Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Proto.Message.Request").msgclass
    Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Proto.Message.Response").msgclass
    UserRegisterRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Proto.Message.UserRegisterRequest").msgclass
    UserRegisterResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Proto.Message.UserRegisterResponse").msgclass
    UserLoginRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Proto.Message.UserLoginRequest").msgclass
    UserLoginResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Proto.Message.UserLoginResponse").msgclass
    PlayerInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Proto.Message.PlayerInput").msgclass
  end
end
