# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("message.proto", :syntax => :proto3) do
    add_message "proto.HeartBeatRequest" do
    end
    add_message "proto.HeartBeatResponse" do
    end
    add_message "proto.NVector3" do
      optional :x, :int32, 1
      optional :y, :int32, 2
      optional :z, :int32, 3
    end
    add_message "proto.NEntity" do
      optional :id, :int32, 1
      optional :position, :message, 2, "proto.NVector3"
      optional :direction, :message, 3, "proto.NVector3"
    end
    add_message "proto.NCharacter" do
      optional :id, :int32, 1
      optional :type_id, :int32, 2
      optional :entity_id, :int32, 3
      optional :name, :string, 4
      optional :level, :int32, 5
      optional :exp, :int64, 6
      optional :spaceId, :int32, 7
      optional :gold, :int64, 8
      optional :entity, :message, 9, "proto.NEntity"
      optional :hp, :int32, 10
      optional :mp, :int32, 11
    end
    add_message "proto.NEntitySync" do
      optional :entity, :message, 1, "proto.NEntity"
      optional :state, :enum, 2, "proto.EntityState"
    end
    add_message "proto.SpaceEntitySyncRequest" do
      optional :entitySync, :message, 1, "proto.NEntitySync"
    end
    add_message "proto.SpaceEntitySyncResponse" do
      optional :entitySync, :message, 1, "proto.NEntitySync"
    end
    add_message "proto.GameEnterRequest" do
      optional :characterId, :int32, 1
    end
    add_message "proto.GameEnterResponse" do
      optional :success, :bool, 1
      optional :entity, :message, 2, "proto.NEntity"
      optional :character, :message, 3, "proto.NCharacter"
    end
    add_message "proto.SpaceCharactersEnterResponse" do
      optional :spaceId, :int32, 1
      repeated :characterList, :message, 2, "proto.NCharacter"
    end
    add_message "proto.SpaceCharacterLeaveResponse" do
      optional :entityId, :int32, 1
    end
    add_message "proto.UserRegisterRequest" do
      optional :username, :string, 1
      optional :password, :string, 2
    end
    add_message "proto.UserRegisterResponse" do
      optional :code, :int32, 1
      optional :message, :string, 2
    end
    add_message "proto.UserLoginRequest" do
      optional :username, :string, 1
      optional :password, :string, 2
    end
    add_message "proto.UserLoginResponse" do
      optional :success, :bool, 3
      optional :code, :int32, 1
      optional :message, :string, 2
    end
    add_message "proto.EntitySyncResponse" do
      repeated :entityList, :message, 1, "proto.NEntity"
    end
    add_message "proto.EntityEnterResponse" do
      optional :entity, :message, 1, "proto.NEntity"
    end
    add_message "proto.CharacterCreateRequest" do
      optional :name, :string, 1
      optional :jobType, :int32, 2
    end
    add_message "proto.ChracterCreateResponse" do
      optional :success, :bool, 1
      optional :message, :string, 2
      optional :character, :message, 3, "proto.NCharacter"
    end
    add_message "proto.CharacterListRequest" do
    end
    add_message "proto.CharacterListResponse" do
      repeated :characterList, :message, 1, "proto.NCharacter"
    end
    add_message "proto.CharacterDeleteRequest" do
      optional :characterId, :int32, 1
    end
    add_message "proto.CharacterDeleteResponse" do
      optional :success, :bool, 1
      optional :message, :string, 2
    end
    add_message "proto.PlayerInput" do
      optional :inputX, :int32, 1
      optional :inputZ, :int32, 2
      optional :mousePosX, :int32, 3
      optional :mousePosZ, :int32, 4
      optional :inputFire, :bool, 5
      optional :skillId, :int32, 6
      optional :inputSpeedUp, :bool, 7
    end
    add_enum "proto.EntityState" do
      value :NONE, 0
      value :IDLE, 1
      value :MOVE, 2
      value :JUMP, 3
    end
  end
end

module Proto
  HeartBeatRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.HeartBeatRequest").msgclass
  HeartBeatResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.HeartBeatResponse").msgclass
  NVector3 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.NVector3").msgclass
  NEntity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.NEntity").msgclass
  NCharacter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.NCharacter").msgclass
  NEntitySync = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.NEntitySync").msgclass
  SpaceEntitySyncRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.SpaceEntitySyncRequest").msgclass
  SpaceEntitySyncResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.SpaceEntitySyncResponse").msgclass
  GameEnterRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.GameEnterRequest").msgclass
  GameEnterResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.GameEnterResponse").msgclass
  SpaceCharactersEnterResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.SpaceCharactersEnterResponse").msgclass
  SpaceCharacterLeaveResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.SpaceCharacterLeaveResponse").msgclass
  UserRegisterRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.UserRegisterRequest").msgclass
  UserRegisterResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.UserRegisterResponse").msgclass
  UserLoginRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.UserLoginRequest").msgclass
  UserLoginResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.UserLoginResponse").msgclass
  EntitySyncResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.EntitySyncResponse").msgclass
  EntityEnterResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.EntityEnterResponse").msgclass
  CharacterCreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CharacterCreateRequest").msgclass
  ChracterCreateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ChracterCreateResponse").msgclass
  CharacterListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CharacterListRequest").msgclass
  CharacterListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CharacterListResponse").msgclass
  CharacterDeleteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CharacterDeleteRequest").msgclass
  CharacterDeleteResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CharacterDeleteResponse").msgclass
  PlayerInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.PlayerInput").msgclass
  EntityState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.EntityState").enummodule
end
