# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\rProto.Message\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01z\x18\x03 \x01(\x05\"w\n\x06\x45ntity\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05speed\x18\x02 \x01(\x05\x12(\n\x08position\x18\x03 \x01(\x0b\x32\x16.Proto.Message.Vector3\x12(\n\x08rotation\x18\x04 \x01(\x0b\x32\x16.Proto.Message.Vector3\"]\n\x07Package\x12\'\n\x07request\x18\x01 \x01(\x0b\x32\x16.Proto.Message.Request\x12)\n\x08response\x18\x02 \x01(\x0b\x32\x17.Proto.Message.Response\"w\n\x07Request\x12\x38\n\x0cuserRegister\x18\x01 \x01(\x0b\x32\".Proto.Message.UserRegisterRequest\x12\x32\n\tuserLogin\x18\x02 \x01(\x0b\x32\x1f.Proto.Message.UserLoginRequest\"z\n\x08Response\x12\x39\n\x0cuserRegister\x18\x01 \x01(\x0b\x32#.Proto.Message.UserRegisterResponse\x12\x33\n\tuserLogin\x18\x02 \x01(\x0b\x32 .Proto.Message.UserLoginResponse\"9\n\x13UserRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"5\n\x14UserRegisterResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"6\n\x10UserLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"2\n\x11UserLoginResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VECTOR3._serialized_start=32
  _VECTOR3._serialized_end=74
  _ENTITY._serialized_start=76
  _ENTITY._serialized_end=195
  _PACKAGE._serialized_start=197
  _PACKAGE._serialized_end=290
  _REQUEST._serialized_start=292
  _REQUEST._serialized_end=411
  _RESPONSE._serialized_start=413
  _RESPONSE._serialized_end=535
  _USERREGISTERREQUEST._serialized_start=537
  _USERREGISTERREQUEST._serialized_end=594
  _USERREGISTERRESPONSE._serialized_start=596
  _USERREGISTERRESPONSE._serialized_end=649
  _USERLOGINREQUEST._serialized_start=651
  _USERLOGINREQUEST._serialized_end=705
  _USERLOGINRESPONSE._serialized_start=707
  _USERLOGINRESPONSE._serialized_end=757
# @@protoc_insertion_point(module_scope)
